pull_request_rules:
  - name: automatic merge for Dependabot 🤖🤖🤖
    conditions:
      - author~=^dependabot\[bot\]$
      - check-success=Run end to end test
    actions:
      merge:
        method: squash