name: 'File Diff'
description: 'Compare the content of 2 files.'
branding:
  icon: align-left
  color: green
inputs:
  lhs:
    description: 'The LHS file to compare'
    required: true
  rhs:
    description: 'The RHS file to compare'
    required: true
  fail:
    description: 'If file diff should fail the action'
    required: false
    default: 'true'
  debug:
    description: 'If debug output should show'
    required: false
    default: 'false'
  compare:
    description: 'If diff compare should show'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'compiled/index.js'